/**
    This file was generated by FSMViewerAvalonia (https://github.com/HKLab/FSMViewAvalonia).
    Generator Type: FSMViewAvalonia2.CodeGen.FsmProxy.DefaultFsmProxy
    **/
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using HutongGames.PlayMaker;

namespace FSMProxy;

internal class FSMProxy_Control
{
    public static class StateNames
    {
        public const string Init = "Init";
        public const string Start_Fall = "Start Fall";
        public const string Start_Land = "Start Land";
        public const string Roar = "Roar";
        public const string Roar_End = "Roar End";
        public const string Roar_Antic = "Roar Antic";
        public const string Roar_Recover = "Roar Recover";
        public const string Hop_Start_Antic = "Hop Start Antic";
        public const string Hop_Start = "Hop Start";
        public const string Hop = "Hop";
        public const string Hop_Land = "Hop Land";
        public const string Hop_Wall = "Hop Wall";
        public const string Set_Hops = "Set Hops";
        public const string Move_Choice = "Move Choice";
        public const string Lunge_Antic = "Lunge Antic";
        public const string Lunge_Launch = "Lunge Launch";
        public const string Lunge_Air = "Lunge Air";
        public const string Lunge_Swipe = "Lunge Swipe";
        public const string Lunge_Recover = "Lunge Recover";
        public const string Jump_Antic = "Jump Antic";
        public const string Jump = "Jump";
        public const string Roof = "Roof";
        public const string Summon = "Summon?";
        public const string Return = "Return";
        public const string Slam = "Slam";
        public const string Spawn = "Spawn";
        public const string Spawn_Recover = "Spawn Recover";
        public const string Resummon_Pause = "Resummon Pause";
        public const string Repos = "Repos";
        public const string Return_Antic = "Return Antic";
        public const string Phase_1 = "Phase 1";
        public const string Buzzer = "Buzzer";
        public const string Resummon = "Resummon?";
        public const string Spitter = "Spitter";
        public const string Roller = "Roller";
        public const string Enemy_Count = "Enemy Count";
        public const string Move_Choice_None = "Move Choice None";
        public const string Stun_Start = "Stun Start";
        public const string Stun_Air = "Stun Air";
        public const string Stun = "Stun";
        public const string Stun_Recover = "Stun Recover";
        public const string Death_Start = "Death Start";
        public const string Stun_Hit = "Stun Hit";
        public const string Sleep = "Sleep";
        public const string Music = "Music";
    }
    public static class VariableNames
    {
        public const string Spawned_One = "Spawned One";
        public const string Bottle_X = "Bottle X";
        public const string Bottle_XL = "Bottle XL";
        public const string Bottle_XR = "Bottle XR";
        public const string Hero_X = "Hero X";
        public const string Hop_Height_Max = "Hop Height Max";
        public const string Hop_Height_Min = "Hop Height Min";
        public const string Hop_X_Speed = "Hop X Speed";
        public const string Hop_X_Speed_Crt = "Hop X Speed Crt";
        public const string Hop_Y_Speed = "Hop Y Speed";
        public const string Last_Bottle_X = "Last Bottle X";
        public const string Resummon_Pause = "Resummon Pause";
        public const string Return_Y = "Return Y";
        public const string Roof_X_L = "Roof X L";
        public const string Roof_X_R = "Roof X R";
        public const string Roof_Y = "Roof Y";
        public const string Self_X = "Self X";
        public const string Self_Y = "Self Y";
        public const string Spawn_Recover_Time = "Spawn Recover Time";
        public const string Stun_Push = "Stun Push";
        public const string Stun_Push_Crt = "Stun Push Crt";
        public const string X_Distance = "X Distance";
        public const string X_Scale = "X Scale";
        public const string Area_Title = "Area Title";
        public const string Buzzer_Prefab = "Buzzer Prefab";
        public const string Buzzers = "Buzzers";
        public const string Dust_Land = "Dust Land";
        public const string Dust_Trail = "Dust Trail";
        public const string Lunge_Hit = "Lunge Hit";
        public const string Ready_Dust = "Ready Dust";
        public const string Roar_Emitter = "Roar Emitter";
        public const string Roar_Point = "Roar Point";
        public const string Roller_Prefab = "Roller Prefab";
        public const string Rollers = "Rollers";
        public const string Self = "Self";
        public const string Slam_Effect = "Slam Effect";
        public const string Spawn_Jar = "Spawn Jar";
        public const string Spitter_Prefab = "Spitter Prefab";
        public const string Spitters = "Spitters";
        public const string Stun_Player = "Stun Player";
        public const string Terrain_Block = "Terrain Block";
        public const string Top_Pool = "Top Pool";
        public const string Boss_Tag_Count = "Boss Tag Count";
        public const string Buzzer_HP = "Buzzer HP";
        public const string Ct_Buzzer = "Ct Buzzer";
        public const string Ct_Jump = "Ct Jump";
        public const string Ct_Jump_2 = "Ct Jump 2";
        public const string Ct_Lunge = "Ct Lunge";
        public const string Ct_Lunge_2 = "Ct Lunge 2";
        public const string Ct_Roller = "Ct Roller";
        public const string Ct_Spitter = "Ct Spitter";
        public const string Current_Enemies = "Current Enemies";
        public const string Enemies_Max = "Enemies Max";
        public const string Hops = "Hops";
        public const string Jars_Spawned = "Jars Spawned";
        public const string Ms_Buzzer = "Ms Buzzer";
        public const string Ms_Roller = "Ms Roller";
        public const string Ms_Spitter = "Ms Spitter";
        public const string Repositions = "Repositions";
        public const string Roller_HP = "Roller HP";
        public const string Spawn_Max = "Spawn Max";
        public const string Spawn_Min = "Spawn Min";
        public const string Spawns_Total = "Spawns Total";
        public const string Spitter_HP = "Spitter HP";
        public const string Hop_Anim_Name = "Hop Anim Name";
        public const string Box_Offset_Idle = "Box Offset Idle";
        public const string Box_Size_Idle = "Box Size Idle";
    }
    public static class EventNames
    {
        public const string FINISHED = "FINISHED";
        public const string BUZZER = "BUZZER";
        public const string BUZZER_ROLLER = "BUZZER ROLLER";
        public const string BUZZER_SPITTER = "BUZZER SPITTER";
        public const string CANCEL = "CANCEL";
        public const string END = "END";
        public const string HOP_END = "HOP END";
        public const string JUMP_AWAY = "JUMP AWAY";
        public const string LAND = "LAND";
        public const string LUNGE = "LUNGE";
        public const string MAX = "MAX";
        public const string NONE = "NONE";
        public const string REPOS = "REPOS";
        public const string ROLLER = "ROLLER";
        public const string SPITTER = "SPITTER";
        public const string SPITTER_ROLLER = "SPITTER ROLLER";
        public const string STUN = "STUN";
        public const string SUMMON = "SUMMON";
        public const string TOOK_DAMAGE = "TOOK DAMAGE";
        public const string WAKE = "WAKE";
        public const string WALL = "WALL";
        public const string ZERO_HP = "ZERO HP";
    }
    public class FsmVariablesHolder
    {
        public FsmVariables fsmVariables;
        public FsmBool Spawned_One
        {
            get
            {
                return fsmVariables.FindFsmBool(VariableNames.Spawned_One);
            }
        }
        public FsmFloat Bottle_X
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Bottle_X);
            }
        }
        public FsmFloat Bottle_XL
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Bottle_XL);
            }
        }
        public FsmFloat Bottle_XR
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Bottle_XR);
            }
        }
        public FsmFloat Hero_X
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Hero_X);
            }
        }
        public FsmFloat Hop_Height_Max
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Hop_Height_Max);
            }
        }
        public FsmFloat Hop_Height_Min
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Hop_Height_Min);
            }
        }
        public FsmFloat Hop_X_Speed
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Hop_X_Speed);
            }
        }
        public FsmFloat Hop_X_Speed_Crt
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Hop_X_Speed_Crt);
            }
        }
        public FsmFloat Hop_Y_Speed
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Hop_Y_Speed);
            }
        }
        public FsmFloat Last_Bottle_X
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Last_Bottle_X);
            }
        }
        public FsmFloat Resummon_Pause
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Resummon_Pause);
            }
        }
        public FsmFloat Return_Y
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Return_Y);
            }
        }
        public FsmFloat Roof_X_L
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Roof_X_L);
            }
        }
        public FsmFloat Roof_X_R
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Roof_X_R);
            }
        }
        public FsmFloat Roof_Y
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Roof_Y);
            }
        }
        public FsmFloat Self_X
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Self_X);
            }
        }
        public FsmFloat Self_Y
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Self_Y);
            }
        }
        public FsmFloat Spawn_Recover_Time
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Spawn_Recover_Time);
            }
        }
        public FsmFloat Stun_Push
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Stun_Push);
            }
        }
        public FsmFloat Stun_Push_Crt
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.Stun_Push_Crt);
            }
        }
        public FsmFloat X_Distance
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.X_Distance);
            }
        }
        public FsmFloat X_Scale
        {
            get
            {
                return fsmVariables.FindFsmFloat(VariableNames.X_Scale);
            }
        }
        public FsmGameObject Area_Title
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Area_Title);
            }
        }
        public FsmGameObject Buzzer_Prefab
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Buzzer_Prefab);
            }
        }
        public FsmGameObject Buzzers
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Buzzers);
            }
        }
        public FsmGameObject Dust_Land
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Dust_Land);
            }
        }
        public FsmGameObject Dust_Trail
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Dust_Trail);
            }
        }
        public FsmGameObject Lunge_Hit
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Lunge_Hit);
            }
        }
        public FsmGameObject Ready_Dust
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Ready_Dust);
            }
        }
        public FsmGameObject Roar_Emitter
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Roar_Emitter);
            }
        }
        public FsmGameObject Roar_Point
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Roar_Point);
            }
        }
        public FsmGameObject Roller_Prefab
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Roller_Prefab);
            }
        }
        public FsmGameObject Rollers
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Rollers);
            }
        }
        public FsmGameObject Self
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Self);
            }
        }
        public FsmGameObject Slam_Effect
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Slam_Effect);
            }
        }
        public FsmGameObject Spawn_Jar
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Spawn_Jar);
            }
        }
        public FsmGameObject Spitter_Prefab
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Spitter_Prefab);
            }
        }
        public FsmGameObject Spitters
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Spitters);
            }
        }
        public FsmGameObject Stun_Player
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Stun_Player);
            }
        }
        public FsmGameObject Terrain_Block
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Terrain_Block);
            }
        }
        public FsmGameObject Top_Pool
        {
            get
            {
                return fsmVariables.FindFsmGameObject(VariableNames.Top_Pool);
            }
        }
        public FsmInt Boss_Tag_Count
        {
            get
            {
                return fsmVariables.FindFsmInt(VariableNames.Boss_Tag_Count);
            }
        }
        public FsmInt Buzzer_HP
        {
            get
            {
                return fsmVariables.FindFsmInt(VariableNames.Buzzer_HP);
            }
        }
        public FsmInt Ct_Buzzer
        {
            get
            {
                return fsmVariables.FindFsmInt(VariableNames.Ct_Buzzer);
            }
        }
        public FsmInt Ct_Jump
        {
            get
            {
                return fsmVariables.FindFsmInt(VariableNames.Ct_Jump);
            }
        }
        public FsmInt Ct_Jump_2
        {
            get
            {
                return fsmVariables.FindFsmInt(VariableNames.Ct_Jump_2);
            }
        }
        public FsmInt Ct_Lunge
        {
            get
            {
                return fsmVariables.FindFsmInt(VariableNames.Ct_Lunge);
            }
        }
        public FsmInt Ct_Lunge_2
        {
            get
            {
                return fsmVariables.FindFsmInt(VariableNames.Ct_Lunge_2);
            }
        }
        public FsmInt Ct_Roller
        {
            get
            {
                return fsmVariables.FindFsmInt(VariableNames.Ct_Roller);
            }
        }
        public FsmInt Ct_Spitter
        {
            get
            {
                return fsmVariables.FindFsmInt(VariableNames.Ct_Spitter);
            }
        }
        public FsmInt Current_Enemies
        {
            get
            {
                return fsmVariables.FindFsmInt(VariableNames.Current_Enemies);
            }
        }
        public FsmInt Enemies_Max
        {
            get
            {
                return fsmVariables.FindFsmInt(VariableNames.Enemies_Max);
            }
        }
        public FsmInt Hops
        {
            get
            {
                return fsmVariables.FindFsmInt(VariableNames.Hops);
            }
        }
        public FsmInt Jars_Spawned
        {
            get
            {
                return fsmVariables.FindFsmInt(VariableNames.Jars_Spawned);
            }
        }
        public FsmInt Ms_Buzzer
        {
            get
            {
                return fsmVariables.FindFsmInt(VariableNames.Ms_Buzzer);
            }
        }
        public FsmInt Ms_Roller
        {
            get
            {
                return fsmVariables.FindFsmInt(VariableNames.Ms_Roller);
            }
        }
        public FsmInt Ms_Spitter
        {
            get
            {
                return fsmVariables.FindFsmInt(VariableNames.Ms_Spitter);
            }
        }
        public FsmInt Repositions
        {
            get
            {
                return fsmVariables.FindFsmInt(VariableNames.Repositions);
            }
        }
        public FsmInt Roller_HP
        {
            get
            {
                return fsmVariables.FindFsmInt(VariableNames.Roller_HP);
            }
        }
        public FsmInt Spawn_Max
        {
            get
            {
                return fsmVariables.FindFsmInt(VariableNames.Spawn_Max);
            }
        }
        public FsmInt Spawn_Min
        {
            get
            {
                return fsmVariables.FindFsmInt(VariableNames.Spawn_Min);
            }
        }
        public FsmInt Spawns_Total
        {
            get
            {
                return fsmVariables.FindFsmInt(VariableNames.Spawns_Total);
            }
        }
        public FsmInt Spitter_HP
        {
            get
            {
                return fsmVariables.FindFsmInt(VariableNames.Spitter_HP);
            }
        }
        public FsmString Hop_Anim_Name
        {
            get
            {
                return fsmVariables.FindFsmString(VariableNames.Hop_Anim_Name);
            }
        }
        public FsmVector2 Box_Offset_Idle
        {
            get
            {
                return fsmVariables.FindFsmVector2(VariableNames.Box_Offset_Idle);
            }
        }
        public FsmVector2 Box_Size_Idle
        {
            get
            {
                return fsmVariables.FindFsmVector2(VariableNames.Box_Size_Idle);
            }
        }
    }
    public Fsm FSM { get; }
    public FsmVariablesHolder Variables { get; }
    public FSMProxy_Control(Fsm fsm)
    {
        this.FSM = fsm;
        this.Variables = new FsmVariablesHolder();
        this.Variables.fsmVariables = fsm.Variables;
    }
    public FSMProxy_Control(PlayMakerFSM fsm) : this(fsm.Fsm) { }
}
